<?php

namespace FabLabBundle\Repository;

/**
 * AdhesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdhesionRepository extends \Doctrine\ORM\EntityRepository
{
}
