<?php

namespace FabLabBundle\Repository;
use FabLabBundle\Entity\Adhesion;
use \DateTime;

/**
 * AdhesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdhesionRepository extends \Doctrine\ORM\EntityRepository
{
    function add($adherent_no, $date, $type){
        $em = $this->getEntityManager();
        $adherent = $em->getRepository('FabLabBundle:Adherent')->findOneByNo($adherent_no);
        $adhesion = new Adhesion();
        $adhesion->adherent = $adherent;
        $adhesion->date = new Datetime($date);
        $adhesion->type = $type;
        $this->save($adhesion);
    }

    function save($adhesion){
        $em = $this->getEntityManager();
        if($adhesion->adherent->type == "professionnel"){
            $adhesion->type = "professionnel";
        }
        if($adhesion->type == "professionnel"){
            $adhesion->price = 100;
            $adhesion->cf = 32;
        } else if($adhesion->type == "particulier"){
            $adhesion->price = 30;
            $adhesion->cf = 16;
        } else {
            $adhesion->price = 15;
            $adhesion->cf = 16;
        }
        $adherent = $adhesion->adherent;
        $adherent->end_adhesion = new Datetime($adhesion->date->format('Y-m-d'));
        $adherent->end_adhesion->modify("+1 year");
        $em->persist($adhesion);
        $em->persist($adherent);
        $em->flush();
        $em->getRepository('FabLabBundle:Adherent')->update_cf($adherent->no);
    }

    function getAllForAdherent($adherentId){
        $query = $this->createQueryBuilder('p')
            ->where('p.adherent = :adherent')
            ->setParameter('adherent', $adherentId)
            ->getQuery();

        return $query->getResult();
    }
}
