<?php

namespace FabLabBundle\Repository;

/**
 * CategorieFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
