<?php

namespace FabLabBundle\Repository;

/**
 * FactureFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
