<?php

namespace FabLabBundle\Repository;
use FabLabBundle\Entity\Produit;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    function add($id, $description, $type, $price, $unite){
        $em = $this->getEntityManager();
        $produit = new Produit();
        $produit->id = $id;
        $produit->description = $description;
        $produit->type = $type;
        $produit->price = $price;
        $produit->unite = $unite;
        $em->persist($produit);
        $em->flush();
        return $produit;
    }
}
