<?php

namespace FabLabBundle\Repository;

/**
 * RechargementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechargementRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllForAdherent($adherentId){
        $query = $this->createQueryBuilder('p')
            ->where('p.adherent = :adherent')
            ->setParameter('adherent', $adherentId)
            ->getQuery();

        return $query->getResult();
    }
}
